### PR TITLE
Feature set midi note length

### PR DESCRIPTION
**Pull request by molleweide**
adds more actions and tries adding a midi set note length mapping.

### CODE REVIEW

**Comment by gwatcha** [comment]
It would be better to create branches for each seperate pull request you will do. Right now the 3 pull requests accumulated into this one, so the 2 previous ones are redundant.

It is also better to use a timeline mode to change the midi length note, so I won't merge this one. 

Also, I'm going to merge some of my own improvements into master so be sure you pull that!

**Comment by molleweide** [comment]
Great!

**Comment by molleweide** [comment]
Yeah, I’m gonna try to put everything in one branch next time.

**Comment by molleweide** [comment]
Btw, could you write the key sequence for setting the note length with timeline mode?

**Comment by gwatcha** [comment]
`["c"] = "FitNotes"`

This works for growing notes as well.

It is similar for items.

To insert an item with a specific length, just do 
    `["i"] = "InsertNote"`

**Comment by molleweide** [comment]
Cool I’ll try this!

**Pull request closed without merging**
