### PR TITLE
add / insert media item

### PR DESCRIPTION
**Pull request by molleweide**
add ability to insert media item...

### CODE REVIEW

**Comment by molleweide** [comment]
My I command seems to be composable!
Holy shiet!

**Comment by gwatcha** [comment]
Thanks! That's useful. 

I'll probably rebind it to 'i' and and move selected item operations under a different key in the future.

**Comment by molleweide** [comment]
Yeah, do whatever you want because you know things best!
I try to add as many useful things as I can for practice.

**Pull request merged**
