### PR TITLE
adds additional actions for set midi grid and key

### PR DESCRIPTION
**Pull request by molleweide**
I have added more actions for setting grid values.
I realized that you have to make sure that both the main and midi grid are
the same value.
I can add also that using the set midi grid actions doesn't seem to do anything.
I had to change the midi grid manually.
I noticed also that setting some grid values seem to fall through and trigger
other commands, such as setting midi grid to 1/4 seems to also delete underlying
item. I am not 100% sure.
Anyways now more grid actions are added.

### CODE REVIEW

**Comment by molleweide** [comment]
Should I have made the PR to the dev branch instead, or am I doing it right?

**Comment by gwatcha** [comment]
Actually, on the develop branch I have removed grid actions and replaced it with <SPC>gg which will bring up a window that one can enter a grid division number.

**Comment by molleweide** [comment]
Cool, I'll check it out

**Comment by molleweide** [comment]
This is super nice. I am going to study the custom actions and see how everything is
done. I like the logging of the state in the console. I was trying to read through
the command and state_machine dirs.

**Pull request closed without merging**
