### PR TITLE
add info about restore standard keys

### PR DESCRIPTION
**Pull request by molleweide**
I wanted to add some info about how one can restore the old key map. It took me
a while at first.

This is my first pull request I have ever done so please tell me if I am doing
something incorrectly.

### CODE REVIEW

**Comment by molleweide** [comment]
for example, I am not sure if I am making the PR on the correct branch.

**Comment by molleweide** [comment]
I think that because I use prettier for formatting it seems like I made a lot of
changes, but I only added one line under the installation section.

**Comment by gwatcha** [comment]
Thanks for doing this! The formatting helps too. You didn't do anything wrong at all!

**Comment by molleweide** [comment]
Cool! I look forward to being able to help more. Using vim bindings for music
programming makes total sense to me. It is going to be interesting to see how
fluid one can become. I have just started using Reaper and reascripting so I'll
help out as much I can and learn along the way.

**Pull request merged**
