### PR TITLE
Feature change volume and pan

### PR DESCRIPTION
**Pull request by molleweide**
Here I try to add basic mixing commands vol and pan.

Tell me if I made these two PR's following what you wrote to me last time about
making two branches.

### CODE REVIEW

**Comment by molleweide** [comment]
Oh wait now I understand what you meant with making two separate branches!!
What I have done here is that I have both branches on the same branch so they aren’t really two. 
I’ll make sure not to do this in the future...

**Comment by gwatcha** [comment]
That's alright! If you're looking for an easier interface to git, I use [magit](https://magit.vc/). It comes with [spacemacs](https://www.spacemacs.org/) that's a text editor with vim bindings. Everything started making a lot more sense when I started using it. Plus it's got vim bindings :)

**Comment by gwatcha** [comment]
I won't merge this commit either because of the new option on the develop branch to set these with a number. There's also a new key '<SPC>,g' which toggles whether the midi and main grids are linked or not.

**Comment by gwatcha** [comment]
I'll add your track mixing functionality manually.

**Comment by molleweide** [comment]
> That's alright! If you're looking for an easier interface to git, I use [magit](https://magit.vc/). It comes with [spacemacs](https://www.spacemacs.org/) that's a text editor with vim bindings. Everything started making a lot more sense when I started using it. Plus it's got vim bindings :)

Cool I have been trying to learn vim for a couple of months now. Did you use emacs or vim before switching to spacemacs? Or both maybe?

**Pull request closed without merging**
