### PR TITLE
make left right move based on grid??

### PR DESCRIPTION
**Pull request by molleweide**
I added all grid set value actions.
I bound L/R glob move to grid as a test.
My idea is that it would be nice to program in piano roll if can change grid?
I'll try to add more actions as I go.

### CODE REVIEW

**Comment by molleweide** [comment]
now all grid values are mapped all over the keyboard so that we have quick access.
it would also be nice to reach the grid values with one key instead of two
with \<SPC\>G.

**Comment by molleweide** [comment]
it would also be nice to grow items/midinotes in a similar fashion.

**Comment by gwatcha** [comment]
I like it! Thanks. 

Btw, I have made a develop branch, you should put your pull requests there from now.

**Comment by molleweide** [comment]
Nice!

**Pull request merged**
